# This is a basic workflow to help you get started with Actions

name: Deploy to Envrironments

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-test:
    runs-on: ubuntu-latest
    environment: test
    env:
      Az_RG_Name: RG20-Test
    steps:
      - uses: actions/checkout@v3
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_TEST}}
      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: [deploy-test]
    env:
      Az_RG_Name: RG20-Prod
    steps:
      - uses: actions/checkout@v3
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'