
name: Deploy Azure Resources

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/workflows/*", "*.ps1" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Bicep linter test
        run: az bicep build --file storage.bicep
        