
name: Deploy Azure Resources

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/workflows/*", "*.ps1" ]
  workflow_dispatch:

env:
  Az_RG_Name: RG10

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Bicep linter test
        run: az bicep build --file storage.bicep
  
  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'
      - name: Deploy sa
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.Az_RG_Name}}
          template: ./storage.bicep
      - name: Deploy Container
        uses: azure/arm-deploy@v1
        id: deploy-sa-container
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.Az_RG_Name}}
          template: ./blobcontainer.bicep
          parameters: mysaname=${{steps.deploy-sa.outputs.mysaname}}